sudo: required

language: generic

services:
  - docker

before_install:
  - ehco "start creating an image with dockerfile"
  - docker build -t jnlee1102/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true jnlee1102/react-app npm run test -- --coverage

after_success:
  - echo "Test success"
