sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t jnlee1102/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true jnlee1102/react-app npm run test -- --coverage

#after_success:
#  - echo "Test success"

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "react-app"
  env: "Reactapp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-250058502806"
  bucket_path: "react-app"
  on:
    branch: master
access_key_id: $AWS_ACCESS_KEY
secert_access_ke: $AWS_SECRET_ACCESS_KEY
